= DokuWiki to AsciiDoc Converter
:source-language: shell
// links
:dw-plugin: https://www.dokuwiki.org/plugin

This project is a converter from DokuWiki to http://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] markup.
It’s the most complete converter between these markups you can find.footnote:[If you know about better, more complete converter from DokuWiki to AsciiDoc, please let me know!]


== Requirements

* Linux system with common userland (Busybox, GNU coreutils, ...)
* http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html[POSIX-sh] compatible shell (e.g. Busybox ash, dash, ZSH, Bash, ...)
* `sed` supporting GNU extensions: `\?`, `\+`, `\|`, `^` inside subexpressions, and `q` with exit code
* Python for rewriting internal links


== Features and Limitations

Most syntactic DokuWiki constructs can be converted to AsciiDoc.

Known limitations in the conversion from DokuWiki to AsciiDoc:

* No syntax checking is done of the input file.
* Appending a downloadable file (code snippet) to a Code block is not available (the link to the file is silently discarded by the converter).
* Anchors (links to a location on the same page) may not work due to different naming conventions.
* The vertical spanning (over several rows) of table cells is not provided.
* Text decorations and “text not to be parsed” marks are only converted if opening and closing marks are on the same line.
* Windows shares and Interwiki links are not converted.
* Embedding HTML and PHP is not available.
* RSS/Atom feed integration is not available.
* Text to image conversion is not available.


=== Supported Plugins

In addition to the basic DokuWiki syntax, the following plugins are supported:

[%header, cols="1,4,4"]
|===
| Plugin
| Limitations
| Notes

| {dw-plugin}:cli[cli]
| All attributes (prompt, comment, continue) are ignored.
| Converted to a source block with lang “sh”.

| {dw-plugin}:code[code]
| No limitations.
| Code title is converted to a block title.

| {dw-plugin}:code2[code2]
| Line number is ignored, no difference between header and footer.
| Header/footer is converted to a block title.

| {dw-plugin}:comment[comment]
| If comment is not properly terminated, the converter terminates with an error.
| Content between the marks is discarded from the output.

| {dw-plugin}:htmlcomment[htmlcomment]
| Recognized only when opening and closing tags are on the same line.
| Content between `++<!--++` and `++-->++` tags is discarded from the output.

| {dw-plugin}:latex[latex], {dw-plugin}:mathjax[mathjax]
| Latex delimiters are not recognized in a nowiki area.

`++$...$++` and `++$$...$$++` are not recognized when opening and closing delimiters are not on the same line.

`++$...$++` is converted only when there’s no alphanumeric character before/after opening/closing `$`, no space after/before opening/closing `$`, and no character with a special meaning after opening `$`.

a| * `++$...$++` is converted to `++stem:[...]++`,
   * `++$$...$$++` is converted to a STEM block,
   * `++<latex>...</latex>++` is converted to `++stem:[...]++` if opened/closed tags are on the same line, otherwise to a STEM block.

| {dw-plugin}:note[note]
| No limitations.
| Note is converted to a corresponding admonition block, or admonition paragraph if

| {dw-plugin}:yalist[yalist]
| Only (un)ordered list item with single extra paragraph denoted by `..` on the line immediately after the list item (`**` or `--`) is supported.
|
|===


== Credits

dokuwiki2adoc is a fork of https://github.com/DidierSpaier/convtags[convtags] created by https://github.com/DidierSpaier/[Didier Spaier] for the http://www.slackware.com/[Slackware Linux Project].
The most essential sed magic in this converter is Didier’s work.
I’ve fixed many bugs and improved it a lot, yet I still don’t understand how exactly some of the tricks with hold space work.
Didier is a real sed master!


== License

This project is licensed under https://spdx.org/licenses/BSD-1-Clause.html[BSD-1-Clause License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
